### ISSUE TITLE
Add support for `report-to` directive

### ISSUE THREAD

**Issue by omerlh** [frux/csp#2]
It seems that `report-uri` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri), and it is good to send both `report-uri` and `report-to` directives to be on the safe side.

Can you please add it? Or will you merge the PR if I'll add it?

**Comment by frux** [comment]
Hi! Thank you for creating this issue. I've just published `csp-header@5.0.0` and `express-csp-header@5.0.0` with `Report-To` header and `report-to` directive support. [Here](https://github.com/frux/csp/tree/master/packages/express-csp-header#csp-violation-report) is an example of usage.

**Comment by omerlh** [comment]
Nice! Thank you :)
