### ISSUE TITLE
Add new CSP constants

### ISSUE THREAD

**Issue by jbebe** [frux/csp#4]
For example we needed `'wasm-unsafe-eval'` and it was sad we couldn't just include it from the lib.

**Comment by frux** [comment]
Hi! Thank you for this issue. Added some constants in v5.2.1
- directive [`webrtc`](https://www.w3.org/TR/CSP3/#directive-webrtc) with keywords `'allow'` and `'block'`
- ['wasm-unsafe-eval'](https://www.w3.org/TR/CSP3/#grammardef-wasm-unsafe-eval)
- ['unsafe-allow-redirects'](https://www.w3.org/TR/CSP3/#grammardef-unsafe-allow-redirects)
- ['report-sample'](https://www.w3.org/TR/CSP3/#grammardef-report-sample)
